version: '2'
services:
    austravel-app:
        image: austravel
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://austravel-mysql:3306/austravel?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    austravel-mysql:
        extends:
            file: mysql.yml
            service: austravel-mysql
